title: GalleyPDF
description: A minimalist PDF previewer for TeX/LaTeX on macOS
url: "https://munepi.github.io"
baseurl: "/Galley"
markdown: kramdown

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
